In [1]:
import pandas as pd

In [2]:
neerslag_csv = r'D:\Projects\RO\0815.10 Data Challenge 2018\Neerslag\neerslag_mm_hr.csv'

In [3]:
df = pd.read_csv(neerslag_csv)
df.set_index('datetime', inplace=True)
df.index = pd.to_datetime(df.index)
df.columns = ['peilvak.{}'.format(ix) for ix in [132, 15, 34, 95, 92, 21, 113, 65, 142, 12, 100, 74]]
df.head()

,peilvak.132,peilvak.15,peilvak.34,peilvak.95,peilvak.92,peilvak.21,peilvak.113,peilvak.65,peilvak.142,peilvak.12,peilvak.100,peilvak.74
datetime,,,,,,,,,,,,
2010-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-01 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-01 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
stuw_csv = r'D:\Projects\RO\0815.10 Data Challenge 2018\Neerslag\stuw_standen_peilvak.csv'
df_stuw = pd.read_csv(stuw_csv)
df_stuw.set_index('datetime', inplace=True)
df_stuw.index = pd.to_datetime(df_stuw.index)
df_stuw = df_stuw.resample('H').mean()
df_stuw.head()

,peilvak.15,peilvak.142,peilvak.95,peilvak.12,peilvak.74,peilvak.132,peilvak.100,peilvak.92,peilvak.21,peilvak.34,peilvak.113,peilvak.65
datetime,,,,,,,,,,,,
2010-01-01 00:00:00,NaN,1.04050,-1.5860,-0.00350,NaN,-1.91125,NaN,-1.26350,-0.52550,NaN,NaN,-1.66650
2010-01-01 01:00:00,NaN,1.00750,-1.5865,-0.00375,NaN,-1.89200,NaN,-1.26400,-0.52525,NaN,NaN,-1.66700
2010-01-01 02:00:00,NaN,0.97675,-1.5880,-0.00425,NaN,-1.88125,NaN,-1.26725,-0.52575,NaN,NaN,-1.66600
2010-01-01 03:00:00,NaN,0.97400,-1.5880,-0.00475,NaN,-1.89200,NaN,-1.26800,-0.52600,NaN,NaN,-1.66225
2010-01-01 04:00:00,NaN,1.01900,-1.5875,-0.00500,NaN,-1.88750,NaN,-1.26675,-0.52575,NaN,NaN,-1.66000

In [5]:
df_1H = df.groupby(pd.TimeGrouper('H')).sum()
df_2H = df_1H.rolling(window = '2H').sum()
df_3H = df_1H.rolling(window = '3H').sum()
df_4H = df_1H.rolling(window = '4H').sum()
df_5H = df_1H.rolling(window = '5H').sum()
df_6H = df_1H.rolling(window = '6H').sum()
df_7H = df_1H.rolling(window = '7H').sum()
df_8H = df_1H.rolling(window = '8H').sum()
df_9H = df_1H.rolling(window = '9H').sum()
df_10H = df_1H.rolling(window = '10H').sum()
df_11H = df_1H.rolling(window = '11H').sum()
df_12H = df_1H.rolling(window = '12H').sum()
df_13H = df_1H.rolling(window = '13H').sum()
df_14H = df_1H.rolling(window = '14H').sum()
df_15H = df_1H.rolling(window = '15H').sum()
df_16H = df_1H.rolling(window = '16H').sum()
df_17H = df_1H.rolling(window = '17H').sum()
df_18H = df_1H.rolling(window = '18H').sum()
df_19H = df_1H.rolling(window = '19H').sum()
df_20H = df_1H.rolling(window = '20H').sum()
df_21H = df_1H.rolling(window = '21H').sum()
df_22H = df_1H.rolling(window = '22H').sum()
df_23H = df_1H.rolling(window = '23H').sum()
df_24H = df_1H.rolling(window = '24H').sum()
df_32H = df_1H.rolling(window = '32H').sum()

df_1H_FC = df_1H.shift(freq= pd.Timedelta('-1 hour'))
df_2H_FC = df_2H.shift(freq= pd.Timedelta('-2 hour'))
df_3H_FC = df_3H.shift(freq= pd.Timedelta('-3 hour'))
df_4H_FC = df_4H.shift(freq= pd.Timedelta('-4 hour'))
df_5H_FC = df_5H.shift(freq= pd.Timedelta('-5 hour'))
df_6H_FC = df_6H.shift(freq= pd.Timedelta('-6 hour')) 

from_date = '2015-08-30 18:00'
to_date = '2015-08-31 08:00'


for peilvak in df_stuw.columns:
    print(peilvak)
    
    comb_peilvak = pd.concat([df_1H[peilvak], df_2H[peilvak], df_4H[peilvak], df_8H[peilvak], df_16H[peilvak], 
                              df_32H[peilvak], df_1H_FC[peilvak], df_2H_FC[peilvak], df_3H_FC[peilvak], 
                              df_4H_FC[peilvak], df_5H_FC[peilvak], df_6H_FC[peilvak]], axis=1)
    comb_peilvak.columns = ['X.last1Hsum', 'X.last2Hsum', 'X.last4Hsum', 'X.last8Hsum', 'X.last16Hsum', 
                            'X.last32Hsum', 'X.coming1Hsum', 'X.coming2Hsum', 'X.coming3Hsum', 
                            'X.coming4Hsum', 'X.coming5Hsum', 'X.coming6Hsum']
    
    df_Y_waterlevel = df_stuw[peilvak]
    df_Y_waterlevel.rename('Y.waterlevel', inplace=True)
    df_comb = pd.concat((comb_peilvak, df_Y_waterlevel), axis=1, join='inner')    
    
    pv_out_csv = r'D:\Projects\RO\0815.10 Data Challenge 2018\Neerslag//__{}.csv'.format(peilvak)
    df_comb.to_csv(pv_out_csv)

c:\python35\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: pd.TimeGrouper is deprecated and will be removed; Please use pd.Grouper(freq=...)
  """Entry point for launching an IPython kernel.

peilvak.15
peilvak.142
peilvak.95
peilvak.12
peilvak.74
peilvak.132
peilvak.100
peilvak.92
peilvak.21
peilvak.34
peilvak.113
peilvak.65

In [ ]:
df_1H = df.groupby(pd.TimeGrouper('H')).sum()
df_2H = df_1H.rolling(window = '2H').sum()
df_3H = df_1H.rolling(window = '3H').sum()
df_4H = df_1H.rolling(window = '4H').sum()
df_5H = df_1H.rolling(window = '5H').sum()
df_6H = df_1H.rolling(window = '6H').sum()
df_7H = df_1H.rolling(window = '7H').sum()
df_8H = df_1H.rolling(window = '8H').sum()
df_9H = df_1H.rolling(window = '9H').sum()
df_10H = df_1H.rolling(window = '10H').sum()
df_11H = df_1H.rolling(window = '11H').sum()
df_12H = df_1H.rolling(window = '12H').sum()
df_13H = df_1H.rolling(window = '13H').sum()
df_14H = df_1H.rolling(window = '14H').sum()
df_15H = df_1H.rolling(window = '15H').sum()
df_16H = df_1H.rolling(window = '16H').sum()
df_17H = df_1H.rolling(window = '17H').sum()
df_18H = df_1H.rolling(window = '18H').sum()
df_19H = df_1H.rolling(window = '19H').sum()
df_20H = df_1H.rolling(window = '20H').sum()
df_21H = df_1H.rolling(window = '21H').sum()
df_22H = df_1H.rolling(window = '22H').sum()
df_23H = df_1H.rolling(window = '23H').sum()
df_24H = df_1H.rolling(window = '24H').sum()
df_32H = df_1H.rolling(window = '32H').sum()

df_1H_FC = df_1H.shift(freq= pd.Timedelta('-1 hour'))
df_2H_FC = df_2H.shift(freq= pd.Timedelta('-2 hour'))
df_3H_FC = df_3H.shift(freq= pd.Timedelta('-3 hour'))
df_4H_FC = df_4H.shift(freq= pd.Timedelta('-4 hour'))
df_5H_FC = df_5H.shift(freq= pd.Timedelta('-5 hour'))
df_6H_FC = df_6H.shift(freq= pd.Timedelta('-6 hour'))

In [ ]:
df_24H.head()

In [ ]:
from_date = '2015-08-30 18:00'
to_date = '2015-08-31 08:00'
peilvak = 'peilvak.12'

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

fig, axes = plt.subplots(nrows=8, ncols=1, figsize=(15,8))

df_1H[from_date:to_date][peilvak].plot(kind='bar', ax=axes[0], title='last 1H sum', sharex=True)
df_1H_FC[from_date:to_date][peilvak].plot(kind='bar', ax=axes[1], title='coming 1H sum')

df_2H[from_date:to_date][peilvak].plot(kind='bar', ax=axes[2], title='last 2H sum')
df_2H_FC[from_date:to_date][peilvak].plot(kind='bar', ax=axes[3], title='coming 2H sum')

df_6H[from_date:to_date][peilvak].plot(kind='bar', ax=axes[4], title='last 6H sum')
df_6H_FC[from_date:to_date][peilvak].plot(kind='bar', ax=axes[5], title='coming 6H sum')

df_12H[from_date:to_date][peilvak].plot(kind='bar', ax=axes[6], title='last 12H sum')
df_24H[from_date:to_date][peilvak].plot(kind='bar', ax=axes[7], title='last 24H sum')
#df_36H[from_date:to_date][peilvak].plot(kind='bar', ax=axes[8], title='last 36H sum')
for ax in axes:
    for bar in ax.patches:
        bar.set_facecolor('#888888')

plt.tight_layout()
plt.show()

In [ ]:
comb_peilvak = pd.concat([df_1H[peilvak], df_2H[peilvak], df_4H[peilvak], df_8H[peilvak], df_16H[peilvak], 
                          df_32H[peilvak], df_1H_FC[peilvak], df_2H_FC[peilvak], df_3H_FC[peilvak], 
                          df_4H_FC[peilvak], df_5H_FC[peilvak], df_6H_FC[peilvak]], axis=1, 
                         names=['X.last1Hsum', 'X.last2Hsum', 'X.last4Hsum', 'X.last8Hsum', 'X.last16Hsum', 
                                'X.last32Hsum', 'X.coming1Hsum', 'X.coming2Hsum', 'X.coming3Hsum', 
                                'X.coming4Hsum', 'X.coming5Hsum', 'X.coming6Hsum'])
# comb_peilvak.columns = ['X.last1Hsum', 'X.last2Hsum', 'X.last4Hsum', 'X.last8Hsum', 'X.last16Hsum', 'X.last32Hsum',
#                         'X.coming1Hsum', 'X.coming2Hsum', 'X.coming3Hsum', 'X.coming4Hsum', 'X.coming5Hsum', 'X.coming6Hsum']

# comb_peilvak = pd.concat([df_1H[peilvak], df_2H[peilvak], df_3H[peilvak], df_4H[peilvak], df_5H[peilvak], df_6H[peilvak],
#                           df_7H[peilvak], df_8H[peilvak], df_9H[peilvak], df_10H[peilvak], df_11H[peilvak], df_12H[peilvak],
#                           df_13H[peilvak], df_14H[peilvak], df_15H[peilvak], df_16H[peilvak], df_17H[peilvak], df_18H[peilvak],
#                           df_19H[peilvak], df_20H[peilvak], df_21H[peilvak], df_22H[peilvak], df_23H[peilvak], df_24H[peilvak],
#                           df_1H_FC[peilvak], df_2H_FC[peilvak], df_3H_FC[peilvak],
#                           df_4H_FC[peilvak], df_5H_FC[peilvak], df_6H_FC[peilvak]], axis=1)
# comb_peilvak.columns = ['X.last1Hsum', 'X.last2Hsum', 'X.last3Hsum', 'X.last4Hsum', 'X.last5Hsum', 'X.last6Hsum',
#                         'X.last7Hsum', 'X.last8Hsum', 'X.last9Hsum', 'X.last10Hsum', 'X.last11Hsum', 'X.last12Hsum',
#                         'X.last13Hsum', 'X.last14Hsum', 'X.last15Hsum', 'X.last16Hsum', 'X.last17Hsum', 'X.last18Hsum',
#                         'X.last19Hsum', 'X.last20Hsum', 'X.last21Hsum', 'X.last22Hsum', 'X.last23Hsum', 'X.last24Hsum',
#                         'X.coming1Hsum', 'X.coming2Hsum', 'X.coming3Hsum', 'X.coming4Hsum', 'X.coming5Hsum', 'X.coming6Hsum']

In [ ]:
df_6H_FC[peilvak].abs()

In [ ]:
comb_peilvak[from_date:to_date].index

In [ ]:
# fig, ax = plt.subplots()
# ax2 = ax.twinx()

# ax.bar(comb_peilvak[from_date:to_date].index, comb_peilvak[from_date:to_date])
# ax2.plot(df_stuw[from_date:to_date]['peilvak.74'].index, df_stuw[from_date:to_date]['peilvak.74'])#, color='green', label='Hold')
# ax.set_xticklabels(df_stuw[from_date:to_date]['peilvak.74'].index)
# ax.legend(loc='best')


# # neerslag
# #ax = comb_peilvak[from_date:to_date].plot(kind='bar', figsize=(16,5))

# # stuwdata
# #df_stuw[from_date:to_date]['peilvak.74'].plot(kind='line', figsize=(16,5), ax=ax)

In [ ]:
stuw_csv = r'D:\Projects\RO\0815.10 Data Challenge 2018\Neerslag\stuw_standen_peilvak.csv'
df_stuw = pd.read_csv(stuw_csv)
df_stuw.set_index('datetime', inplace=True)
df_stuw.index = pd.to_datetime(df_stuw.index)
df_stuw = df_stuw.resample('H').mean()

In [ ]:
df_Y_waterlevel = df_stuw[peilvak]
df_Y_waterlevel.rename('Y.waterlevel', inplace=True)
df_comb = pd.concat((comb_peilvak, df_Y_waterlevel), axis=1, join='inner')

In [ ]:
#df_comb[df_comb < 0] = 0

In [ ]:
from_date = '2015-08-28 18:00'
to_date = '2015-09-02 08:00'

df_comb[from_date:to_date][df_comb.columns.difference(['Y.waterlevel'])].abs().plot(kind='area', figsize=(14,3), stacked=False, alpha=0.3, legend=False)
plt.show()
df_comb[from_date:to_date]['Y.waterlevel'].plot(kind='line', figsize=(14,3))

In [ ]:
peilvak

In [ ]:

pv_out_csv = r'D:\Projects\RO\0815.10 Data Challenge 2018\Neerslag//{}.csv'.format(peilvak)

In [ ]:
pv_out_csv = r'D:\Projects\RO\0815.10 Data Challenge 2018\Neerslag//{}.csv'.format(peilvak)
df_comb.to_csv(pv_out_csv)