In [2]:
import pandas as pd
import geopandas as gpd
from glob import glob
%matplotlib inline

In [3]:
station1 = r"D:\Projects\Pr\2505.12\Eduvizig\Sensor stations (waterstandlocaties)\stations_bak.shp"
station2 = r"D:\Projects\Pr\2505.12\Eduvizig\Sensor stations (waterstandlocaties)\stations.shp"
gdf_station1 = gpd.read_file(station1)
gdf_station2 = gpd.read_file(station2)

In [5]:
gdf_stations = pd.merge(gdf_station1, gdf_station2, left_on='name', right_on='name')
gdf_stations.head()

,id_x,lat,lon,max_waterl,min_waterl,name,river_km,stream,threshold_,threshol_1,threshol_2,waterlevel,zero_level,geometry_x,id_y,source,geom_LAT,geom_LONG,code,geometry_y
0,16495FD9-97AB-11D4-BB62-00508BA24287,48.004240,17.247160,648.0,-325.0,Rajka,1848.400,Duna,0.0,0.0,0.0,23.0,122.58,POINT (17.24715951 48.00424006),1,eduvizig,48.004240,17.247,16495FD9-97AB-11D4-BB62-00508BA24287,POINT (17.24715951 48.00424006)
1,16496015-97AB-11D4-BB62-00508BA24287,47.989265,17.322742,1615.0,911.0,"Dunakiliti duzzasztó, felvíz",1842.300,Duna,0.0,0.0,0.0,1284.0,110.00,POINT (17.32274204 47.9892652),21,eduvizig,47.989265,17.323,16496015-97AB-11D4-BB62-00508BA24287,POINT (17.32274204 47.9892652)
2,73F7E3D6-985C-11D4-BB62-00508BA24287,47.977973,17.351301,1497.0,617.0,Doborgaz,1839.500,Duna,0.0,0.0,0.0,791.0,110.00,POINT (17.35130115 47.97797321),24,eduvizig,47.977973,17.351,73F7E3D6-985C-11D4-BB62-00508BA24287,POINT (17.35130115 47.97797321)
3,16495FDA-97AB-11D4-BB62-00508BA24287,47.880347,17.463756,722.0,-39.0,Dunaremete,1825.500,Duna,530.0,580.0,620.0,33.0,113.24,POINT (17.46375629 47.8803474),2,eduvizig,47.880347,17.464,16495FDA-97AB-11D4-BB62-00508BA24287,POINT (17.46375629 47.8803474)
4,16495FDB-97AB-11D4-BB62-00508BA24287,47.760535,17.702123,908.0,-53.0,Nagybajcs,1801.000,Duna,470.0,540.0,610.0,76.0,107.40,POINT (17.70212263 47.76053488),3,eduvizig,47.760535,17.702,16495FDB-97AB-11D4-BB62-00508BA24287,POINT (17.70212263 47.76053488)

In [11]:
df_all = pd.DataFrame()
collection = []
for row in gdf_stations.iterrows():
    loc = row[1]
    loc_info = {
        'stationid':loc.id_y,
        'min':int(loc['min_waterl']), 
        'max':int(loc['max_waterl']), 
        '0_thd': loc['threshold_'], 
        '1_thd': loc['threshol_1'], 
        '2_thd': loc['threshol_2']
    }
    thd_level = {
        '0_thd': 0/3, 
        '1_thd': 1/3, 
        '2_thd': 2/3
    }
    
    if loc_info['0_thd'] == 0 and loc_info['1_thd'] == 0 and loc_info['2_thd'] == 0:
        waterlevel_divid = (loc_info['max'] - loc_info['min']) / 8
        loc_info['0_thd'] = loc_info['min'] + (5 * waterlevel_divid)
        loc_info['1_thd'] = loc_info['min'] + (6 * waterlevel_divid)        
        loc_info['2_thd'] = loc_info['min'] + (7 * waterlevel_divid)                
    
    print(loc['name'], loc.id_y, loc_info)
    

    for key in loc_info.keys():
        dic = {}
        dic.update({'objectid': loc_info['stationid']})
        dic.update({'objecttype': 'measuringstation'})

        if key == '0_thd':
            dic.update({'stateid': 1})                
            dic.update({'upperboundary':loc_info[key]})
            dic.update({'name': '5XP1Y'})
            dic.update({'description': '5 times a year'})
            dic.update({'color': '#daeef3'})     
            collection.append(dic)
        if key == '1_thd':
            dic.update({'stateid': 2})                        
            dic.update({'upperboundary':loc_info[key]})
            dic.update({'name': '5XP1J'})
            dic.update({'name': '1XP30Y'})
            dic.update({'description': '1 times a 30 year'})        
            dic.update({'color': '#4bacc6'})        
            collection.append(dic)
        if key == '2_thd':
            dic.update({'stateid': 3})
            dic.update({'upperboundary':loc_info[key]})
            dic.update({'name': '1XP100Y'})
            dic.update({'description': '1 times a 100 year'})        
            dic.update({'color': '#31849b'})          
            collection.append(dic)
        if key == 'max':
            dic.update({'stateid': 4})        
            dic.update({'upperboundary':loc_info[key]})
            dic.update({'name': '1XP1000Y'})
            dic.update({'description': '1 times a 1000 year'})        
            dic.update({'color': '#002060'})          
            collection.append(dic)

Rajka 1 {'stationid': 1, 'min': -325, 'max': 648, '0_thd': 283.125, '1_thd': 404.75, '2_thd': 526.375}
Dunakiliti duzzasztó, felvíz 21 {'stationid': 21, 'min': 911, 'max': 1615, '0_thd': 1351.0, '1_thd': 1439.0, '2_thd': 1527.0}
Doborgaz 24 {'stationid': 24, 'min': 617, 'max': 1497, '0_thd': 1167.0, '1_thd': 1277.0, '2_thd': 1387.0}
Dunaremete 2 {'stationid': 2, 'min': -39, 'max': 722, '0_thd': 530.0, '1_thd': 580.0, '2_thd': 620.0}
Nagybajcs 3 {'stationid': 3, 'min': -53, 'max': 908, '0_thd': 470.0, '1_thd': 540.0, '2_thd': 610.0}
Gönyû 4 {'stationid': 4, 'min': -92, 'max': 857, '0_thd': 501.125, '1_thd': 619.75, '2_thd': 738.375}
Komárom 5 {'stationid': 5, 'min': 22, 'max': 845, '0_thd': 500.0, '1_thd': 620.0, '2_thd': 680.0}
Esztergom 6 {'stationid': 6, 'min': 13, 'max': 813, '0_thd': 500.0, '1_thd': 600.0, '2_thd': 650.0}
Fertõszéli zsilip felvíz 23 {'stationid': 23, 'min': 93, 'max': 241, '0_thd': 185.5, '1_thd': 204.0, '2_thd': 222.5}
Fertõszéli zsilip alvíz 26 {'stationid': 26, 'min': -18, 'max': 276, '0_thd': 165.75, '1_thd': 202.5, '2_thd': 239.25}
Dunakiliti, Helena-gát 25 {'stationid': 25, 'min': 1097, 'max': 1641, '0_thd': 1437.0, '1_thd': 1505.0, '2_thd': 1573.0}
Mosonmagyaróvár duzzasztó, alvíz /Lajta/ 13 {'stationid': 13, 'min': 0, 'max': 315, '0_thd': 160.0, '1_thd': 200.0, '2_thd': 220.0}
Mórichida 16 {'stationid': 16, 'min': -90, 'max': 391, '0_thd': 250.0, '1_thd': 300.0, '2_thd': 350.0}
Gyirmót (szvtp. Külvíz) 17 {'stationid': 17, 'min': -11, 'max': 630, '0_thd': 320.0, '1_thd': 400.0, '2_thd': 480.0}
Rajka 1. zsilip felvíz 19 {'stationid': 19, 'min': 1258, 'max': 1973, '0_thd': 1704.875, '1_thd': 1794.25, '2_thd': 1883.625}
Rajka 6. zsilip alvíz 18 {'stationid': 18, 'min': 1273, 'max': 1460, '0_thd': 1389.875, '1_thd': 1413.25, '2_thd': 1436.625}
Mecsér 11 {'stationid': 11, 'min': 0, 'max': 520, '0_thd': 325.0, '1_thd': 390.0, '2_thd': 455.0}
Bácsa 12 {'stationid': 12, 'min': -41, 'max': 840, '0_thd': 450.0, '1_thd': 550.0, '2_thd': 600.0}
Ragyogóhíd 7 {'stationid': 7, 'min': -152, 'max': 450, '0_thd': 150.0, '1_thd': 250.0, '2_thd': 300.0}
Vág 8 {'stationid': 8, 'min': -119, 'max': 456, '0_thd': 250.0, '1_thd': 300.0, '2_thd': 350.0}
Árpás 9 {'stationid': 9, 'min': -156, 'max': 586, '0_thd': 320.0, '1_thd': 420.0, '2_thd': 480.0}
Gyõr 10 {'stationid': 10, 'min': 8, 'max': 838, '0_thd': 500.0, '1_thd': 600.0, '2_thd': 650.0}
Rábcakapi 14 {'stationid': 14, 'min': 46, 'max': 434, '0_thd': 250.0, '1_thd': 300.0, '2_thd': 350.0}
Répcelak-Újhíd 15 {'stationid': 15, 'min': -5, 'max': 422, '0_thd': 250.0, '1_thd': 300.0, '2_thd': 350.0}
Rajka 5. zsilip, alvíz 22 {'stationid': 22, 'min': 1078, 'max': 1576, '0_thd': 1389.25, '1_thd': 1451.5, '2_thd': 1513.75}
Rajka 2. zsilip felvíz 20 {'stationid': 20, 'min': 1499, 'max': 1636, '0_thd': 1584.625, '1_thd': 1601.75, '2_thd': 1618.875}

In [12]:
df = pd.DataFrame(collection)

In [15]:
df = df[['stateid', 'objectid', 'objecttype', 'upperboundary', 'name', 'description', 'color']].sort_values(['objectid','stateid'])
df.head()

,stateid,objectid,objecttype,upperboundary,name,description,color
1,1,1,measuringstation,283.125,5XP1Y,5 times a year,#daeef3
2,2,1,measuringstation,404.750,1XP30Y,1 times a 30 year,#4bacc6
3,3,1,measuringstation,526.375,1XP100Y,1 times a 100 year,#31849b
0,4,1,measuringstation,648.000,1XP1000Y,1 times a 1000 year,#002060
13,1,2,measuringstation,530.000,5XP1Y,5 times a year,#daeef3

In [16]:
df.to_csv(r'P:\PR\3730.10\Werkzaamheden\PR3730.15_IT\Data\Eduvizig\conditions_2.csv', index=False)